import type { Metadata } from "next";
import { DM_Serif_Display, Onest } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { cn } from "@/lib/utils";
import Footer from "@/components/footer";

const dmSerifDisplay = DM_Serif_Display({
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
  weight: "400",
});

const oneset = Onest({
  variable: "--font-onset",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(dmSerifDisplay.variable, oneset.variable, "relative 2xl:max-w-[1440px] 2xl:mx-auto")}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
